AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  linebot-openai-chat

Parameters:
  LineChannelAccessToken:
    Type: String
  LineChannelSecret:
    Type: String
  NumOfHistory:
    Type: String
    Default: '10'
  OpenAiApiKey:
    Type: String
  OpenAiModelName:
    Type: String
    Default: gpt-3.5-turbo

Globals:
  Function:
    Timeout: 120
    MemorySize: 512

Resources:
  LineBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: line_bot/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
          LINE_CHANNEL_SECRET: !Ref LineChannelSecret
          NUM_OF_HISTORY: !Ref NumOfHistory
          OPENAI_API_KEY: !Ref OpenAiApiKey
          OPENAI_MODEL_NAME: !Ref OpenAiModelName
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: SessionId
          AttributeType: S
      KeySchema: 
        - AttributeName: SessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  FunctionUrl:
    Value:
      Fn::GetAtt: LineBotFunctionUrl.FunctionUrl
